{
 "title": "Beacons",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Beacon Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "inspectit_eum_self_beacons_received_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg duration of all beacons",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(sum_over_time(inspectit_eum_self_beacons_processor_duration_sum[$__interval]) / sum_over_time(inspectit_eum_self_beacons_processor_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(inspectit_eum_self_beacons_processor_duration_sum[$__interval]) / avg_over_time(inspectit_eum_self_beacons_processor_count[$__interval])",
     "legendFormat": "{{beacon_processor}}"
    }
   ]
  },
  {
   "title": "Beacon Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(inspectit_eum_self_beacons_processor_duration_sum[$__interval]) / avg_over_time(inspectit_eum_self_beacons_processor_count[$__interval])",
     "legendFormat": "{{beacon_processor}}"
    }
   ]
  }
 ]
}