{
 "title": "Trace Controller",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Received Traces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "inspectit_eum_self_traces_received_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Processing Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(inspectit_eum_self_traces_received_duration_sum[$__interval]) / avg_over_time(inspectit_eum_self_traces_received_count[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "inspectit_eum_self_traces_received_count{is_error=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Traces and Error Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "inspectit_eum_self_traces_received_count{is_error=\"false\"}",
     "legendFormat": "Successful Traces"
    },
    {
     "expr": "inspectit_eum_self_traces_received_count{is_error=\"true\"}",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Average Duration of Traces",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(inspectit_eum_self_traces_received_duration_sum[$__interval]) / avg_over_time(inspectit_eum_self_traces_received_count[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spans per Request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "inspectit_eum_self_traces_span_size_sum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}